name: Create Semantic Tag

on:
  push:
    branches:
      - master

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get last tag semver
        run: |
          LAST_TAG=$(git describe --abbrev=0 --tags)
          IFS='.' read -ra VERSION <<< "$LAST_TAG"
          MAJOR=${VERSION[0]}
          MINOR=${VERSION[1]}
          PATCH=${VERSION[2]}
          PATCH=$((PATCH+1))
          NEW_TAG="$MAJOR.$MINOR.$PATCH"
          git tag -a "v$NEW_TAG" -m "Version $NEW_TAG"
          git push origin "v$NEW_TAG"
